/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectakhir;


import javax.swing.*;
import java.awt.*;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author ACER
 */
public class iniAdmin1 extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    
    
    public iniAdmin1() {
        initComponents();
       
        setFont();
        jPanelTop1.putClientProperty( FlatClientProperties.STYLE, "arc: 16" );
       
        jPanelCenter1.putClientProperty( FlatClientProperties.STYLE, "arc: 16" );
        jPanelProfileShapeAdmin.putClientProperty( FlatClientProperties.STYLE, "arc: 100" );
       
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    
  
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCenter = new javax.swing.JPanel();
        jPanelCenter1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanelCreateRecipe1 = new javax.swing.JPanel();
        jTextFieldNamaKuliner = new javax.swing.JTextField();
        jLabelNamaKuliner = new javax.swing.JLabel();
        jLabelBahanUtama = new javax.swing.JLabel();
        jTextFieldBahanUtama = new javax.swing.JTextField();
        jLabelTotalHargaBahan = new javax.swing.JLabel();
        jTextFieldTotalHargaBahan = new javax.swing.JTextField();
        jLabelAsal = new javax.swing.JLabel();
        jComboBoxAsal = new javax.swing.JComboBox<>();
        jLabelLangkah = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaLangkah = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanelCreateRecipe2 = new javax.swing.JPanel();
        jLabelSejarah = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreajLabelSejarah = new javax.swing.JTextArea();
        jLabelDeskripsi1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaDeskripsi1 = new javax.swing.JTextArea();
        jButtonSubmit = new javax.swing.JButton();
        jPanelTop = new javax.swing.JPanel();
        jPanelTop1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelNamaUserHome = new javax.swing.JLabel();
        jLabelKata = new javax.swing.JLabel();
        jPanelProfileShapeAdmin = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(974, 656));

        jPanelCenter.setBackground(new java.awt.Color(242, 242, 238));

        jPanelCenter1.setBackground(new java.awt.Color(242, 242, 238));

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 934, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Draft", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanelCreateRecipe1.setBackground(new java.awt.Color(255, 255, 255));

        jTextFieldNamaKuliner.setBackground(new java.awt.Color(242, 242, 238));

        jLabelNamaKuliner.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNamaKuliner.setText("Nama Coulinary");

        jLabelBahanUtama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelBahanUtama.setText("Bahan Utama");

        jTextFieldBahanUtama.setBackground(new java.awt.Color(242, 242, 238));

        jLabelTotalHargaBahan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTotalHargaBahan.setText("Total Harga Bahan");

        jTextFieldTotalHargaBahan.setBackground(new java.awt.Color(242, 242, 238));
        jTextFieldTotalHargaBahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalHargaBahanActionPerformed(evt);
            }
        });

        jLabelAsal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAsal.setText("Asal");

        jComboBoxAsal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelLangkah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelLangkah.setText("Bahan-bahan/Langkah-langkah");

        jTextAreaLangkah.setColumns(20);
        jTextAreaLangkah.setRows(5);
        jScrollPane2.setViewportView(jTextAreaLangkah);

        javax.swing.GroupLayout jPanelCreateRecipe1Layout = new javax.swing.GroupLayout(jPanelCreateRecipe1);
        jPanelCreateRecipe1.setLayout(jPanelCreateRecipe1Layout);
        jPanelCreateRecipe1Layout.setHorizontalGroup(
            jPanelCreateRecipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreateRecipe1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanelCreateRecipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCreateRecipe1Layout.createSequentialGroup()
                        .addGroup(jPanelCreateRecipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCreateRecipe1Layout.createSequentialGroup()
                                .addComponent(jTextFieldNamaKuliner, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldTotalHargaBahan))
                            .addGroup(jPanelCreateRecipe1Layout.createSequentialGroup()
                                .addGroup(jPanelCreateRecipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelBahanUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldBahanUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelCreateRecipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxAsal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanelCreateRecipe1Layout.createSequentialGroup()
                                        .addComponent(jLabelAsal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 43, Short.MAX_VALUE))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(45, 45, 45))
                    .addGroup(jPanelCreateRecipe1Layout.createSequentialGroup()
                        .addGroup(jPanelCreateRecipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLangkah, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCreateRecipe1Layout.createSequentialGroup()
                                .addComponent(jLabelNamaKuliner, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(433, 433, 433)
                                .addComponent(jLabelTotalHargaBahan, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelCreateRecipe1Layout.setVerticalGroup(
            jPanelCreateRecipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreateRecipe1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCreateRecipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNamaKuliner, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotalHargaBahan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreateRecipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNamaKuliner, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTotalHargaBahan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCreateRecipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBahanUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAsal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreateRecipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBahanUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAsal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabelLangkah, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 954, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelCreateRecipe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelCreateRecipe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Resep", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanelCreateRecipe2.setBackground(new java.awt.Color(255, 255, 255));

        jLabelSejarah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSejarah.setText("Sejarah Singkat Kuliner");

        jTextAreajLabelSejarah.setColumns(20);
        jTextAreajLabelSejarah.setRows(5);
        jScrollPane3.setViewportView(jTextAreajLabelSejarah);

        jLabelDeskripsi1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDeskripsi1.setText("Deskripsi Kuliner");

        jTextAreaDeskripsi1.setColumns(20);
        jTextAreaDeskripsi1.setRows(5);
        jScrollPane4.setViewportView(jTextAreaDeskripsi1);

        jButtonSubmit.setBackground(new java.awt.Color(2, 97, 60));
        jButtonSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSubmit.setText("Submit");

        javax.swing.GroupLayout jPanelCreateRecipe2Layout = new javax.swing.GroupLayout(jPanelCreateRecipe2);
        jPanelCreateRecipe2.setLayout(jPanelCreateRecipe2Layout);
        jPanelCreateRecipe2Layout.setHorizontalGroup(
            jPanelCreateRecipe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreateRecipe2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanelCreateRecipe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCreateRecipe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                        .addComponent(jLabelDeskripsi1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSejarah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanelCreateRecipe2Layout.setVerticalGroup(
            jPanelCreateRecipe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreateRecipe2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabelSejarah, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDeskripsi1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 954, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(43, Short.MAX_VALUE)
                    .addComponent(jPanelCreateRecipe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(44, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCreateRecipe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Deskripsi", jPanel4);

        javax.swing.GroupLayout jPanelCenter1Layout = new javax.swing.GroupLayout(jPanelCenter1);
        jPanelCenter1.setLayout(jPanelCenter1Layout);
        jPanelCenter1Layout.setHorizontalGroup(
            jPanelCenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenter1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelCenter1Layout.setVerticalGroup(
            jPanelCenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenter1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCenterLayout = new javax.swing.GroupLayout(jPanelCenter);
        jPanelCenter.setLayout(jPanelCenterLayout);
        jPanelCenterLayout.setHorizontalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCenter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanelCenterLayout.setVerticalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCenter1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jPanelTop.setBackground(new java.awt.Color(242, 242, 238));

        jPanelTop1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jLabelNamaUserHome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelNamaUserHome.setText("ini Nama");
        jPanel1.add(jLabelNamaUserHome);

        jLabelKata.setText("cobaaaa");
        jPanel1.add(jLabelKata);

        jPanelProfileShapeAdmin.setBackground(new java.awt.Color(2, 97, 60));
        jPanelProfileShapeAdmin.setPreferredSize(new java.awt.Dimension(54, 54));

        javax.swing.GroupLayout jPanelProfileShapeAdminLayout = new javax.swing.GroupLayout(jPanelProfileShapeAdmin);
        jPanelProfileShapeAdmin.setLayout(jPanelProfileShapeAdminLayout);
        jPanelProfileShapeAdminLayout.setHorizontalGroup(
            jPanelProfileShapeAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );
        jPanelProfileShapeAdminLayout.setVerticalGroup(
            jPanelProfileShapeAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelTop1Layout = new javax.swing.GroupLayout(jPanelTop1);
        jPanelTop1.setLayout(jPanelTop1Layout);
        jPanelTop1Layout.setHorizontalGroup(
            jPanelTop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTop1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanelProfileShapeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(449, Short.MAX_VALUE))
        );
        jPanelTop1Layout.setVerticalGroup(
            jPanelTop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTop1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelTop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jPanelProfileShapeAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelTop, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTotalHargaBahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalHargaBahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalHargaBahanActionPerformed
    private void setFont(){
        try{
            File fontStyle = new File("src/font/Poppins-Regular.ttf");
            File fontStyleSB = new File("src/font/Poppins-SemiBold.ttf");
            File fontStyleM = new File("src/font/Poppins-Medium.ttf");
            Font fontm18 = Font.createFont(Font.TRUETYPE_FONT, fontStyleM).deriveFont(18f);
            Font fontm12 = Font.createFont(Font.TRUETYPE_FONT, fontStyleM).deriveFont(12f);
            Font fontsb40 = Font.createFont(Font.TRUETYPE_FONT, fontStyleSB).deriveFont(40f);
            
            Font fontRegular12 = Font.createFont(Font.TRUETYPE_FONT, fontStyle).deriveFont(12f);
            Font font1 = Font.createFont(Font.TRUETYPE_FONT, fontStyle).deriveFont(24f);
            
            
            
            
           
            jLabelNamaUserHome.setForeground(Color.black);
            jLabelNamaUserHome.setFont(fontm18);
            jLabelKata.setForeground(Color.black);
            jLabelKata.setFont(fontRegular12);
            
        }catch(Exception e){
            e.printStackTrace(); 
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
//            UIManager.put( "TextComponent.arc", 10 );
            UIManager.put( "Button.arc", 10 );
            UIManager.put( "TextComponent.arc", 10 );
            UIManager.put( "ScrollBar.width", 5 );
//            UIManager.put("Button.border", BorderFactory.createLineBorder(Color.RED));
  

        } catch (Exception e) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new iniAdmin1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JComboBox<String> jComboBoxAsal;
    private javax.swing.JLabel jLabelAsal;
    private javax.swing.JLabel jLabelBahanUtama;
    private javax.swing.JLabel jLabelDeskripsi1;
    private javax.swing.JLabel jLabelKata;
    private javax.swing.JLabel jLabelLangkah;
    private javax.swing.JLabel jLabelNamaKuliner;
    private javax.swing.JLabel jLabelNamaUserHome;
    private javax.swing.JLabel jLabelSejarah;
    private javax.swing.JLabel jLabelTotalHargaBahan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelCenter1;
    private javax.swing.JPanel jPanelCreateRecipe1;
    private javax.swing.JPanel jPanelCreateRecipe2;
    private javax.swing.JPanel jPanelProfileShapeAdmin;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JPanel jPanelTop1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaDeskripsi1;
    private javax.swing.JTextArea jTextAreaLangkah;
    private javax.swing.JTextArea jTextAreajLabelSejarah;
    private javax.swing.JTextField jTextFieldBahanUtama;
    private javax.swing.JTextField jTextFieldNamaKuliner;
    private javax.swing.JTextField jTextFieldTotalHargaBahan;
    // End of variables declaration//GEN-END:variables
}
