/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectakhir;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import javax.swing.UIManager;

/**
 *
 * @author acer
 */
public class registerPage extends javax.swing.JFrame {


    public registerPage() {
        initComponents();
        jPanelYellowHomePage.setBackground(Color.decode("#e99d28"));
        jPanelYellowHomePage.putClientProperty( FlatClientProperties.STYLE, "arc: 16" );
//        jButtonRegisterUser.setBorder(BorderFactory.createLineBorder(Color.decode("#02613c"), 2));
        jPanelRed.setVisible(true);
        jPanelYellow.setVisible(false);
        jPanelGreen.setVisible(false);
        
        try{
            File fontStyle = new File("src/font/Poppins-Regular.ttf");
            File fontStyleSB = new File("src/font/Poppins-SemiBold.ttf");
            File fontStyleM = new File("src/font/Poppins-Medium.ttf");
            Font fontm16 = Font.createFont(Font.TRUETYPE_FONT, fontStyleM).deriveFont(16f);
            Font fontsb40 = Font.createFont(Font.TRUETYPE_FONT, fontStyleSB).deriveFont(40f);
            
            Font fontRegular14 = Font.createFont(Font.TRUETYPE_FONT, fontStyle).deriveFont(14f);
            Font font1 = Font.createFont(Font.TRUETYPE_FONT, fontStyle).deriveFont(24f);
            
            jLabelLoginPage.setForeground(Color.black);
            jLabelLoginPage.setFont(fontsb40);
            jLabelLoginPage1.setFont(fontsb40);
            jButtonUserRegisterYellow.setFont(fontm16);
            jButtonUserLoginYellow.setFont(fontm16);
            
            jLabelUsernameUserRegister.setFont(fontRegular14);
            jLabelUsernameUserRegister.setForeground(Color.decode("#7D7D7D"));
            jLabelPasswordUserRegister.setFont(fontRegular14);
            jLabelPasswordUserRegister.setForeground(Color.decode("#7D7D7D"));
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldUsernameUserRegister = new javax.swing.JTextField();
        jButtonUserRegisterYellow = new javax.swing.JButton();
        jButtonUserLoginYellow = new javax.swing.JButton();
        jLabelUsernameUserRegister = new javax.swing.JLabel();
        jLabelPasswordUserRegister = new javax.swing.JLabel();
        jPasswordFieldUserRegister = new javax.swing.JPasswordField();
        jLabelLoginPage = new javax.swing.JLabel();
        jLabelLoginPage1 = new javax.swing.JLabel();
        jPanelSafePass = new javax.swing.JPanel();
        jPanelRed = new javax.swing.JPanel();
        jPanelYellow = new javax.swing.JPanel();
        jPanelGreen = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanelYellowHomePage = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(949, 616));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(508, 616));

        jButtonUserRegisterYellow.setBackground(new java.awt.Color(233, 157, 40));
        jButtonUserRegisterYellow.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUserRegisterYellow.setText("Register");
        jButtonUserRegisterYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserRegisterYellowActionPerformed(evt);
            }
        });

        jButtonUserLoginYellow.setForeground(new java.awt.Color(233, 157, 40));
        jButtonUserLoginYellow.setText("Login");
        jButtonUserLoginYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserLoginYellowActionPerformed(evt);
            }
        });

        jLabelUsernameUserRegister.setText("username");

        jLabelPasswordUserRegister.setText("password");

        jPasswordFieldUserRegister.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordFieldUserRegisterKeyTyped(evt);
            }
        });

        jLabelLoginPage.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelLoginPage.setText("Dude!");

        jLabelLoginPage1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelLoginPage1.setText("Welcome Back");

        jPanelSafePass.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSafePass.setLayout(new java.awt.GridLayout());

        jPanelRed.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanelRedLayout = new javax.swing.GroupLayout(jPanelRed);
        jPanelRed.setLayout(jPanelRedLayout);
        jPanelRedLayout.setHorizontalGroup(
            jPanelRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );
        jPanelRedLayout.setVerticalGroup(
            jPanelRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanelSafePass.add(jPanelRed);

        jPanelYellow.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanelYellowLayout = new javax.swing.GroupLayout(jPanelYellow);
        jPanelYellow.setLayout(jPanelYellowLayout);
        jPanelYellowLayout.setHorizontalGroup(
            jPanelYellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );
        jPanelYellowLayout.setVerticalGroup(
            jPanelYellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanelSafePass.add(jPanelYellow);

        jPanelGreen.setBackground(new java.awt.Color(102, 255, 0));

        javax.swing.GroupLayout jPanelGreenLayout = new javax.swing.GroupLayout(jPanelGreen);
        jPanelGreen.setLayout(jPanelGreenLayout);
        jPanelGreenLayout.setHorizontalGroup(
            jPanelGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );
        jPanelGreenLayout.setVerticalGroup(
            jPanelGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanelSafePass.add(jPanelGreen);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSafePass, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLoginPage)
                    .addComponent(jLabelPasswordUserRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsernameUserRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLoginPage1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldUsernameUserRegister, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                        .addComponent(jPasswordFieldUserRegister, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonUserRegisterYellow, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonUserLoginYellow, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabelLoginPage1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLoginPage, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabelUsernameUserRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUsernameUserRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPasswordUserRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldUserRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelSafePass, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUserRegisterYellow, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUserLoginYellow, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(251, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanelYellowHomePage.setBackground(new java.awt.Color(233, 157, 40));
        jPanelYellowHomePage.setMinimumSize(new java.awt.Dimension(432, 604));

        javax.swing.GroupLayout jPanelYellowHomePageLayout = new javax.swing.GroupLayout(jPanelYellowHomePage);
        jPanelYellowHomePage.setLayout(jPanelYellowHomePageLayout);
        jPanelYellowHomePageLayout.setHorizontalGroup(
            jPanelYellowHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );
        jPanelYellowHomePageLayout.setVerticalGroup(
            jPanelYellowHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelYellowHomePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelYellowHomePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUserLoginYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserLoginYellowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUserLoginYellowActionPerformed

    private void jButtonUserRegisterYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserRegisterYellowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUserRegisterYellowActionPerformed

    private void jPasswordFieldUserRegisterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldUserRegisterKeyTyped
        // TODO add your handling code here:
        char[] password = jPasswordFieldUserRegister.getPassword();
        int length = password.length;
        System.out.println("panjang : " + length);
        
        if(length < 5){
            jPanelRed.setVisible(true);
            jPanelYellow.setVisible(false);
            jPanelGreen.setVisible(false);
        }
        else if(length < 8){
            jPanelRed.setVisible(true);
            jPanelYellow.setVisible(true);
            jPanelGreen.setVisible(false);
        }
        else {
            jPanelRed.setVisible(true);
            jPanelYellow.setVisible(true);
            jPanelGreen.setVisible(true);
        }
    }//GEN-LAST:event_jPasswordFieldUserRegisterKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
            UIManager.put( "TextComponent.arc", 10 );
            UIManager.put( "Button.arc", 10 );
//            UIManager.put("Button.border", BorderFactory.createLineBorder(Color.RED));
            
        } catch (Exception e) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUserLoginYellow;
    private javax.swing.JButton jButtonUserRegisterYellow;
    private javax.swing.JLabel jLabelLoginPage;
    private javax.swing.JLabel jLabelLoginPage1;
    private javax.swing.JLabel jLabelPasswordUserRegister;
    private javax.swing.JLabel jLabelUsernameUserRegister;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelGreen;
    private javax.swing.JPanel jPanelRed;
    private javax.swing.JPanel jPanelSafePass;
    private javax.swing.JPanel jPanelYellow;
    private javax.swing.JPanel jPanelYellowHomePage;
    private javax.swing.JPasswordField jPasswordFieldUserRegister;
    private javax.swing.JTextField jTextFieldUsernameUserRegister;
    // End of variables declaration//GEN-END:variables
}
