/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iniapotek;
import javax.swing.*;  
import java.awt.*;  
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.ui.FlatRoundBorder;
import java.io.File;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author Admin
 */
public class tokoObat extends javax.swing.JFrame {
    int detail = 0;
    
    
   
   
    public tokoObat() {
        initComponents();
        jButtonBox1.setVisible(false);
        jButtonBox2.setVisible(false);
        jButtonBox3.setVisible(false);
        jButtonBox4.setVisible(false);
        jButtonBox5.setVisible(false);
        jButtonBox6.setVisible(false);
        jButtonBox7.setVisible(false);
        jButtonBox8.setVisible(false);
        jButtonBox9.setVisible(false);
        
        try{
            File fontStyle = new File("src/iniapotek/Poppins-Regular.ttf");
            Font font18 = Font.createFont(Font.TRUETYPE_FONT, fontStyle).deriveFont(18f);
            Font font12 = Font.createFont(Font.TRUETYPE_FONT, fontStyle).deriveFont(12f);
            Font font36 = Font.createFont(Font.TRUETYPE_FONT, fontStyle).deriveFont(36f);
            jLabelPilihObat.setFont(font18);
            jButtonBox1.setFont(font12);
            jButtonBox2.setFont(font12);
            jButtonBox3.setFont(font12);
            jButtonBox4.setFont(font12);
            jButtonBox5.setFont(font12);
            jButtonBox6.setFont(font12);
            jButtonBox7.setFont(font12);
            jButtonBox8.setFont(font12);
            jButtonBox9.setFont(font12);
        }catch(Exception e){
            e.printStackTrace();
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRight = new javax.swing.JPanel();
        jPanel2 = new RoundedPanel(15, new Color(255,255,255));
        jPanel3 = new RoundedPanel(15, new Color(0,0,0));
        jLabelPilihObat = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanelBox1 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox1 = new javax.swing.JButton();
        jLabelBox1 = new javax.swing.JLabel();
        jPanelBox2 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox2 = new javax.swing.JButton();
        jLabelBox2 = new javax.swing.JLabel();
        jPanelBox3 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox3 = new javax.swing.JButton();
        jLabelBox3 = new javax.swing.JLabel();
        jPanelBox4 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox4 = new javax.swing.JButton();
        jLabelBox4 = new javax.swing.JLabel();
        jPanelBox5 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox5 = new javax.swing.JButton();
        jLabelBox5 = new javax.swing.JLabel();
        jPanelBox6 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox6 = new javax.swing.JButton();
        jLabelBox6 = new javax.swing.JLabel();
        jPanelBox7 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox7 = new javax.swing.JButton();
        jLabelBox7 = new javax.swing.JLabel();
        jPanelBox8 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox8 = new javax.swing.JButton();
        jLabelBox8 = new javax.swing.JLabel();
        jPanelBox9 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox9 = new javax.swing.JButton();
        jLabelBox9 = new javax.swing.JLabel();
        jPanel5 = new RoundedPanel(15, new Color(242,242,242));
        jLabelDetailGambar = new javax.swing.JLabel();
        jLabelDetailTittle = new javax.swing.JLabel();
        jButtonBeli = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabelTotal = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneDetail = new javax.swing.JTextPane();
        jPanel6 = new RoundedPanel(15, new Color(0,0,0));
        jLabelDetail = new javax.swing.JLabel();
        jPanelLeft = new javax.swing.JPanel();
        jPanel1 = new RoundedPanel(15, new Color(0,0,0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(917, 591));
        setPreferredSize(new java.awt.Dimension(917, 591));

        jPanelRight.setPreferredSize(new java.awt.Dimension(757, 551));
        jPanelRight.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(760, 511));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabelPilihObat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelPilihObat.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPilihObat.setText("Pilih Obat");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPilihObat, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPilihObat, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 430, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(3, 3, 20, 20));

        jPanelBox1.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox1.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox1.setText("detail");
        jButtonBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox1MouseEntered(evt);
            }
        });
        jButtonBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox1ActionPerformed(evt);
            }
        });
        jPanelBox1.add(jButtonBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/1.png"))); // NOI18N
        jLabelBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox1MouseExited(evt);
            }
        });
        jPanelBox1.add(jLabelBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanel4.add(jPanelBox1);

        jPanelBox2.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox2.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox2.setText("detail");
        jButtonBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox2MouseEntered(evt);
            }
        });
        jButtonBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox2ActionPerformed(evt);
            }
        });
        jPanelBox2.add(jButtonBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/2.png"))); // NOI18N
        jLabelBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox2MouseExited(evt);
            }
        });
        jPanelBox2.add(jLabelBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanel4.add(jPanelBox2);

        jPanelBox3.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox3.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox3.setText("detail");
        jButtonBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox3MouseEntered(evt);
            }
        });
        jButtonBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox3ActionPerformed(evt);
            }
        });
        jPanelBox3.add(jButtonBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/3.png"))); // NOI18N
        jLabelBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox3MouseExited(evt);
            }
        });
        jPanelBox3.add(jLabelBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanel4.add(jPanelBox3);

        jPanelBox4.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox4.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox4.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox4.setText("detail");
        jButtonBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox4MouseEntered(evt);
            }
        });
        jButtonBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox4ActionPerformed(evt);
            }
        });
        jPanelBox4.add(jButtonBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/4.png"))); // NOI18N
        jLabelBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox4MouseExited(evt);
            }
        });
        jPanelBox4.add(jLabelBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanel4.add(jPanelBox4);

        jPanelBox5.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox5.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox5.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox5.setText("detail");
        jButtonBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox5MouseEntered(evt);
            }
        });
        jButtonBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox5ActionPerformed(evt);
            }
        });
        jPanelBox5.add(jButtonBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/5.png"))); // NOI18N
        jLabelBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox5MouseExited(evt);
            }
        });
        jPanelBox5.add(jLabelBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanel4.add(jPanelBox5);

        jPanelBox6.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox6.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox6.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox6.setText("detail");
        jButtonBox6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox6MouseEntered(evt);
            }
        });
        jButtonBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox6ActionPerformed(evt);
            }
        });
        jPanelBox6.add(jButtonBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/6.png"))); // NOI18N
        jLabelBox6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox6MouseExited(evt);
            }
        });
        jPanelBox6.add(jLabelBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanel4.add(jPanelBox6);

        jPanelBox7.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox7.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox7.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox7.setText("detail");
        jButtonBox7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox7MouseEntered(evt);
            }
        });
        jButtonBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox7ActionPerformed(evt);
            }
        });
        jPanelBox7.add(jButtonBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/7.png"))); // NOI18N
        jLabelBox7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox7MouseExited(evt);
            }
        });
        jPanelBox7.add(jLabelBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanel4.add(jPanelBox7);

        jPanelBox8.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox8.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox8.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox8.setText("detail");
        jButtonBox8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox8MouseEntered(evt);
            }
        });
        jButtonBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox8ActionPerformed(evt);
            }
        });
        jPanelBox8.add(jButtonBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/8.png"))); // NOI18N
        jLabelBox8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox8MouseExited(evt);
            }
        });
        jPanelBox8.add(jLabelBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanel4.add(jPanelBox8);

        jPanelBox9.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox9.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox9.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox9.setText("detail");
        jButtonBox9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox9MouseEntered(evt);
            }
        });
        jButtonBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox9ActionPerformed(evt);
            }
        });
        jPanelBox9.add(jButtonBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/9.png"))); // NOI18N
        jLabelBox9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox9MouseExited(evt);
            }
        });
        jPanelBox9.add(jLabelBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanel4.add(jPanelBox9);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 430, 410));

        jLabelDetailGambar.setPreferredSize(new java.awt.Dimension(130, 16));

        jLabelDetailTittle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelDetailTittle.setText("jLabel3");

        jButtonBeli.setText("Beli");

        jButtonCancel.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabelTotal.setText("Total");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextPaneDetail.setEditable(false);
        jScrollPane2.setViewportView(jTextPaneDetail);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButtonBeli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                        .addComponent(jTextField1))))
                            .addComponent(jLabelDetailTittle, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabelDetailGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelDetailGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDetailTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 240, 410));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabelDetail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelDetail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDetail.setText("Detail");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 240, 30));

        jPanelRight.add(jPanel2);
        jPanel2.setBounds(20, 20, 760, 510);

        getContentPane().add(jPanelRight, java.awt.BorderLayout.CENTER);

        jPanelLeft.setPreferredSize(new java.awt.Dimension(100, 551));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelLeft, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabelBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox1MouseEntered
        // TODO add your handling code here:
        jButtonBox1.setVisible(true);
    }//GEN-LAST:event_jLabelBox1MouseEntered

    private void jLabelBox1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox1MouseExited
        // TODO add your handling code here:
        jButtonBox1.setVisible(false);
    }//GEN-LAST:event_jLabelBox1MouseExited

    private void jButtonBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox1MouseEntered
        // TODO add your handling code here:
        jButtonBox1.setVisible(true);
    }//GEN-LAST:event_jButtonBox1MouseEntered

    private void jButtonBox2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox2MouseEntered
        // TODO add your handling code here:
        jButtonBox2.setVisible(true);
    }//GEN-LAST:event_jButtonBox2MouseEntered

    private void jLabelBox2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox2MouseEntered
        // TODO add your handling code here:
         jButtonBox2.setVisible(true);
    }//GEN-LAST:event_jLabelBox2MouseEntered

    private void jLabelBox2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox2MouseExited
        // TODO add your handling code here:
         jButtonBox2.setVisible(false);
    }//GEN-LAST:event_jLabelBox2MouseExited

    private void jButtonBox3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox3MouseEntered
        // TODO add your handling code here:
         jButtonBox3.setVisible(true);
    }//GEN-LAST:event_jButtonBox3MouseEntered

    private void jLabelBox3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox3MouseEntered
        // TODO add your handling code here:
        jButtonBox3.setVisible(true);
    }//GEN-LAST:event_jLabelBox3MouseEntered

    private void jLabelBox3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox3MouseExited
        // TODO add your handling code here:
        jButtonBox3.setVisible(false);
    }//GEN-LAST:event_jLabelBox3MouseExited

    private void jButtonBox4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox4MouseEntered
        // TODO add your handling code here:
        jButtonBox4.setVisible(true);
    }//GEN-LAST:event_jButtonBox4MouseEntered

    private void jLabelBox4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox4MouseEntered
        // TODO add your handling code here:
        jButtonBox4.setVisible(true);
    }//GEN-LAST:event_jLabelBox4MouseEntered

    private void jLabelBox4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox4MouseExited
        // TODO add your handling code here:
        jButtonBox4.setVisible(false);
    }//GEN-LAST:event_jLabelBox4MouseExited

    private void jButtonBox5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox5MouseEntered
        // TODO add your handling code here:
        jButtonBox5.setVisible(true);
    }//GEN-LAST:event_jButtonBox5MouseEntered

    private void jLabelBox5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox5MouseEntered
        // TODO add your handling code here:
        jButtonBox5.setVisible(true);
    }//GEN-LAST:event_jLabelBox5MouseEntered

    private void jLabelBox5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox5MouseExited
        // TODO add your handling code here:
        jButtonBox5.setVisible(false);
    }//GEN-LAST:event_jLabelBox5MouseExited

    private void jButtonBox6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox6MouseEntered
        // TODO add your handling code here:
        jButtonBox6.setVisible(true);
    }//GEN-LAST:event_jButtonBox6MouseEntered

    private void jLabelBox6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox6MouseEntered
        // TODO add your handling code here:
        jButtonBox6.setVisible(true);
    }//GEN-LAST:event_jLabelBox6MouseEntered

    private void jLabelBox6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox6MouseExited
        // TODO add your handling code here:
        jButtonBox6.setVisible(false);
    }//GEN-LAST:event_jLabelBox6MouseExited

    private void jButtonBox7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox7MouseEntered
        // TODO add your handling code here:
        jButtonBox7.setVisible(true);
    }//GEN-LAST:event_jButtonBox7MouseEntered

    private void jLabelBox7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox7MouseEntered
        // TODO add your handling code here:
        jButtonBox7.setVisible(true);
    }//GEN-LAST:event_jLabelBox7MouseEntered

    private void jLabelBox7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox7MouseExited
        // TODO add your handling code here:
        jButtonBox7.setVisible(false);
    }//GEN-LAST:event_jLabelBox7MouseExited

    private void jButtonBox8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox8MouseEntered
        // TODO add your handling code here:
        jButtonBox8.setVisible(true);
    }//GEN-LAST:event_jButtonBox8MouseEntered

    private void jLabelBox8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox8MouseEntered
        // TODO add your handling code here:
        jButtonBox8.setVisible(true);
    }//GEN-LAST:event_jLabelBox8MouseEntered

    private void jLabelBox8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox8MouseExited
        // TODO add your handling code here:
        jButtonBox8.setVisible(false);
    }//GEN-LAST:event_jLabelBox8MouseExited

    private void jButtonBox9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox9MouseEntered
        // TODO add your handling code here:
        jButtonBox9.setVisible(true);
    }//GEN-LAST:event_jButtonBox9MouseEntered

    private void jLabelBox9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox9MouseEntered
        // TODO add your handling code here:
        jButtonBox9.setVisible(true);
    }//GEN-LAST:event_jLabelBox9MouseEntered

    private void jLabelBox9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox9MouseExited
        // TODO add your handling code here:
        jButtonBox9.setVisible(false);
    }//GEN-LAST:event_jLabelBox9MouseExited

    private void jButtonBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox1ActionPerformed
        // TODO add your handling code here:
        detail = 1;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
        jTextPaneDetail.setText("Paracetamol 500mg\n" +
"Obat pereda nyeri dan demam\n" +
"Efektif untuk mengurangi rasa\n" +
"nyeri, aman untuk digunakan.");

    }//GEN-LAST:event_jButtonBox1ActionPerformed

    private void jButtonBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox2ActionPerformed
        // TODO add your handling code here:
        detail = 2;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
    }//GEN-LAST:event_jButtonBox2ActionPerformed

    private void jButtonBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox3ActionPerformed
        // TODO add your handling code here:
        detail = 3;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
    }//GEN-LAST:event_jButtonBox3ActionPerformed

    private void jButtonBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox4ActionPerformed
        // TODO add your handling code here:
        detail = 4;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
    }//GEN-LAST:event_jButtonBox4ActionPerformed

    private void jButtonBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox5ActionPerformed
        // TODO add your handling code here:
        detail = 5;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
    }//GEN-LAST:event_jButtonBox5ActionPerformed

    private void jButtonBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox6ActionPerformed
        // TODO add your handling code here:
        detail = 6;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
    }//GEN-LAST:event_jButtonBox6ActionPerformed

    private void jButtonBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox7ActionPerformed
        // TODO add your handling code here:
        detail = 7;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
    }//GEN-LAST:event_jButtonBox7ActionPerformed

    private void jButtonBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox8ActionPerformed
        // TODO add your handling code here:
        detail = 8;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
    }//GEN-LAST:event_jButtonBox8ActionPerformed

    private void jButtonBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox9ActionPerformed
        // TODO add your handling code here:
        detail = 9;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
    }//GEN-LAST:event_jButtonBox9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // Mengatur Look and Feel ke FlatLightLaf
            UIManager.setLookAndFeel(new FlatLightLaf());

            // Mengatur sudut lengkung untuk tombol dan panel
//            UIManager.put("Button.border", BorderFactory.createEmptyBorder());


            UIManager.put("Button.arc", 15);  
            


            

        } catch (Exception e) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tokoObat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBeli;
    private javax.swing.JButton jButtonBox1;
    private javax.swing.JButton jButtonBox2;
    private javax.swing.JButton jButtonBox3;
    private javax.swing.JButton jButtonBox4;
    private javax.swing.JButton jButtonBox5;
    private javax.swing.JButton jButtonBox6;
    private javax.swing.JButton jButtonBox7;
    private javax.swing.JButton jButtonBox8;
    private javax.swing.JButton jButtonBox9;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JLabel jLabelBox1;
    private javax.swing.JLabel jLabelBox2;
    private javax.swing.JLabel jLabelBox3;
    private javax.swing.JLabel jLabelBox4;
    private javax.swing.JLabel jLabelBox5;
    private javax.swing.JLabel jLabelBox6;
    private javax.swing.JLabel jLabelBox7;
    private javax.swing.JLabel jLabelBox8;
    private javax.swing.JLabel jLabelBox9;
    private javax.swing.JLabel jLabelDetail;
    private javax.swing.JLabel jLabelDetailGambar;
    private javax.swing.JLabel jLabelDetailTittle;
    private javax.swing.JLabel jLabelPilihObat;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelBox1;
    private javax.swing.JPanel jPanelBox2;
    private javax.swing.JPanel jPanelBox3;
    private javax.swing.JPanel jPanelBox4;
    private javax.swing.JPanel jPanelBox5;
    private javax.swing.JPanel jPanelBox6;
    private javax.swing.JPanel jPanelBox7;
    private javax.swing.JPanel jPanelBox8;
    private javax.swing.JPanel jPanelBox9;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPaneDetail;
    // End of variables declaration//GEN-END:variables
}
