/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iniapotek;
import javax.swing.*;  
import java.awt.*;  
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.ui.FlatRoundBorder;
import java.io.File;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author Admin
 */
public class tokoObat1 extends javax.swing.JFrame {
    int detail = 0;
    
    
   
   
    public tokoObat1() {
        initComponents();
        jButtonBox1.setVisible(false);
        jButtonBox2.setVisible(false);
        jButtonBox3.setVisible(false);
        jButtonBox4.setVisible(false);
        jButtonBox5.setVisible(false);
        jButtonBox6.setVisible(false);
        jButtonBox7.setVisible(false);
        jButtonBox8.setVisible(false);
        jButtonBox9.setVisible(false);
        jButtonBox10.setVisible(false);
        jButtonBox11.setVisible(false);
        jButtonBox12.setVisible(false);
        jButtonBox13.setVisible(false);
        jButtonBox14.setVisible(false);
        jButtonBox15.setVisible(false);
        jButtonBox16.setVisible(false);
        jButtonBox17.setVisible(false);
        jButtonBox18.setVisible(false);
        jButtonBox19.setVisible(false);
        jPanelFull.setVisible(true);
        jPanelFlu.setVisible(false);
        jPanelBatuk.setVisible(false);
        
        
        try{
            File fontStyle = new File("src/iniapotek/Poppins-Regular.ttf");
            Font font18 = Font.createFont(Font.TRUETYPE_FONT, fontStyle).deriveFont(18f);
            Font font12 = Font.createFont(Font.TRUETYPE_FONT, fontStyle).deriveFont(12f);
            Font font36 = Font.createFont(Font.TRUETYPE_FONT, fontStyle).deriveFont(36f);
            jLabelPilihObat.setFont(font18);
            jButtonBox1.setFont(font12);
            jButtonBox2.setFont(font12);
            jButtonBox3.setFont(font12);
            jButtonBox4.setFont(font12);
            jButtonBox5.setFont(font12);
            jButtonBox6.setFont(font12);
            jButtonBox7.setFont(font12);
            jButtonBox8.setFont(font12);
            jButtonBox9.setFont(font12);
            jButtonAll.setFont(font12);
            jButtonFlu.setFont(font12);
            jButtonBatuk.setFont(font12);
        }catch(Exception e){
            e.printStackTrace();
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRight = new javax.swing.JPanel();
        jPanel2 = new RoundedPanel(15, new Color(255,255,255));
        jPanel3 = new RoundedPanel(15, new Color(0,0,0));
        jLabelPilihObat = new javax.swing.JLabel();
        jPanel5 = new RoundedPanel(15, new Color(242,242,242));
        jLabelDetailGambar = new javax.swing.JLabel();
        jLabelDetailTittle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneDetail = new javax.swing.JTextPane();
        jPanel6 = new RoundedPanel(15, new Color(0,0,0));
        jLabelDetail = new javax.swing.JLabel();
        jPanelFull = new javax.swing.JPanel();
        jPanelBox1 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox1 = new javax.swing.JButton();
        jLabelBox1 = new javax.swing.JLabel();
        jPanelBox2 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox2 = new javax.swing.JButton();
        jLabelBox2 = new javax.swing.JLabel();
        jPanelBox3 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox3 = new javax.swing.JButton();
        jLabelBox3 = new javax.swing.JLabel();
        jPanelBox4 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox4 = new javax.swing.JButton();
        jLabelBox4 = new javax.swing.JLabel();
        jPanelBox5 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox5 = new javax.swing.JButton();
        jLabelBox5 = new javax.swing.JLabel();
        jPanelBox6 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox6 = new javax.swing.JButton();
        jLabelBox6 = new javax.swing.JLabel();
        jPanelBox7 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox7 = new javax.swing.JButton();
        jLabelBox7 = new javax.swing.JLabel();
        jPanelBox8 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox8 = new javax.swing.JButton();
        jLabelBox8 = new javax.swing.JLabel();
        jPanelBox9 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox9 = new javax.swing.JButton();
        jLabelBox9 = new javax.swing.JLabel();
        jPanelFlu = new javax.swing.JPanel();
        jPanelBox19 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox15 = new javax.swing.JButton();
        jLabelBox15 = new javax.swing.JLabel();
        jPanelBox20 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox16 = new javax.swing.JButton();
        jLabelBox16 = new javax.swing.JLabel();
        jPanelBox21 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox17 = new javax.swing.JButton();
        jLabelBox17 = new javax.swing.JLabel();
        jPanelBox22 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox18 = new javax.swing.JButton();
        jLabelBox18 = new javax.swing.JLabel();
        jPanelBox23 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox19 = new javax.swing.JButton();
        jLabelBox19 = new javax.swing.JLabel();
        jPanelBox24 = new RoundedPanel(15, new Color(255,255,255));
        jPanelBox25 = new RoundedPanel(15, new Color(255,255,255));
        jPanelBox26 = new RoundedPanel(15, new Color(255,255,255));
        jPanelBox27 = new RoundedPanel(15, new Color(255,255,255));
        jPanelBatuk = new javax.swing.JPanel();
        jPanelBox10 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox10 = new javax.swing.JButton();
        jLabelBox10 = new javax.swing.JLabel();
        jPanelBox11 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox11 = new javax.swing.JButton();
        jLabelBox11 = new javax.swing.JLabel();
        jPanelBox12 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox12 = new javax.swing.JButton();
        jLabelBox12 = new javax.swing.JLabel();
        jPanelBox13 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox13 = new javax.swing.JButton();
        jLabelBox13 = new javax.swing.JLabel();
        jPanelBox14 = new RoundedPanel(15, new Color(242,242,242));
        jButtonBox14 = new javax.swing.JButton();
        jLabelBox14 = new javax.swing.JLabel();
        jPanelBox15 = new RoundedPanel(15, new Color(255,255,255));
        jPanelBox16 = new RoundedPanel(15, new Color(255,255,255));
        jPanelBox17 = new RoundedPanel(15, new Color(255,255,255));
        jPanelBox18 = new RoundedPanel(15, new Color(255,255,255));
        jButtonBatuk = new javax.swing.JButton();
        jButtonAll = new javax.swing.JButton();
        jButtonFlu = new javax.swing.JButton();
        jPanelLeft = new javax.swing.JPanel();
        jPanel1 = new RoundedPanel(15, new Color(0,0,0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(917, 591));

        jPanelRight.setPreferredSize(new java.awt.Dimension(757, 551));
        jPanelRight.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(760, 511));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabelPilihObat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelPilihObat.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPilihObat.setText("Pilih Obat");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPilihObat, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPilihObat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 430, 30));

        jLabelDetailGambar.setPreferredSize(new java.awt.Dimension(130, 16));

        jLabelDetailTittle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextPaneDetail.setEditable(false);
        jScrollPane2.setViewportView(jTextPaneDetail);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelDetailTittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabelDetailGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelDetailGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDetailTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 240, 300));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabelDetail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelDetail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDetail.setText("Detail");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 240, 30));

        jPanelFull.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFull.setLayout(new java.awt.GridLayout(3, 3, 20, 20));

        jPanelBox1.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox1.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox1.setText("detail");
        jButtonBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox1MouseEntered(evt);
            }
        });
        jButtonBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox1ActionPerformed(evt);
            }
        });
        jPanelBox1.add(jButtonBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/1.png"))); // NOI18N
        jLabelBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox1MouseExited(evt);
            }
        });
        jPanelBox1.add(jLabelBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanelFull.add(jPanelBox1);

        jPanelBox2.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox2.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox2.setText("detail");
        jButtonBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox2MouseEntered(evt);
            }
        });
        jButtonBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox2ActionPerformed(evt);
            }
        });
        jPanelBox2.add(jButtonBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/2.png"))); // NOI18N
        jLabelBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox2MouseExited(evt);
            }
        });
        jPanelBox2.add(jLabelBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanelFull.add(jPanelBox2);

        jPanelBox3.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox3.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox3.setText("detail");
        jButtonBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox3MouseEntered(evt);
            }
        });
        jButtonBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox3ActionPerformed(evt);
            }
        });
        jPanelBox3.add(jButtonBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/3.png"))); // NOI18N
        jLabelBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox3MouseExited(evt);
            }
        });
        jPanelBox3.add(jLabelBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanelFull.add(jPanelBox3);

        jPanelBox4.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox4.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox4.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox4.setText("detail");
        jButtonBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox4MouseEntered(evt);
            }
        });
        jButtonBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox4ActionPerformed(evt);
            }
        });
        jPanelBox4.add(jButtonBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/4.png"))); // NOI18N
        jLabelBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox4MouseExited(evt);
            }
        });
        jPanelBox4.add(jLabelBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanelFull.add(jPanelBox4);

        jPanelBox5.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox5.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox5.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox5.setText("detail");
        jButtonBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox5MouseEntered(evt);
            }
        });
        jButtonBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox5ActionPerformed(evt);
            }
        });
        jPanelBox5.add(jButtonBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/5.png"))); // NOI18N
        jLabelBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox5MouseExited(evt);
            }
        });
        jPanelBox5.add(jLabelBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanelFull.add(jPanelBox5);

        jPanelBox6.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox6.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox6.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox6.setText("detail");
        jButtonBox6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox6MouseEntered(evt);
            }
        });
        jButtonBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox6ActionPerformed(evt);
            }
        });
        jPanelBox6.add(jButtonBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/6.png"))); // NOI18N
        jLabelBox6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox6MouseExited(evt);
            }
        });
        jPanelBox6.add(jLabelBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanelFull.add(jPanelBox6);

        jPanelBox7.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox7.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox7.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox7.setText("detail");
        jButtonBox7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox7MouseEntered(evt);
            }
        });
        jButtonBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox7ActionPerformed(evt);
            }
        });
        jPanelBox7.add(jButtonBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/7.png"))); // NOI18N
        jLabelBox7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox7MouseExited(evt);
            }
        });
        jPanelBox7.add(jLabelBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanelFull.add(jPanelBox7);

        jPanelBox8.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox8.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox8.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox8.setText("detail");
        jButtonBox8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox8MouseEntered(evt);
            }
        });
        jButtonBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox8ActionPerformed(evt);
            }
        });
        jPanelBox8.add(jButtonBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/8.png"))); // NOI18N
        jLabelBox8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox8MouseExited(evt);
            }
        });
        jPanelBox8.add(jLabelBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanelFull.add(jPanelBox8);

        jPanelBox9.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox9.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox9.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox9.setText("detail");
        jButtonBox9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox9MouseEntered(evt);
            }
        });
        jButtonBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox9ActionPerformed(evt);
            }
        });
        jPanelBox9.add(jButtonBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/9.png"))); // NOI18N
        jLabelBox9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox9MouseExited(evt);
            }
        });
        jPanelBox9.add(jLabelBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanelFull.add(jPanelBox9);

        jPanel2.add(jPanelFull, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 430, 410));

        jPanelFlu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFlu.setLayout(new java.awt.GridLayout(3, 3, 20, 20));

        jPanelBox19.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox15.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox15.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox15.setText("detail");
        jButtonBox15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox15MouseEntered(evt);
            }
        });
        jButtonBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox15ActionPerformed(evt);
            }
        });
        jPanelBox19.add(jButtonBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/6.png"))); // NOI18N
        jLabelBox15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox15MouseExited(evt);
            }
        });
        jPanelBox19.add(jLabelBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanelFlu.add(jPanelBox19);

        jPanelBox20.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox16.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox16.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox16.setText("detail");
        jButtonBox16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox16MouseEntered(evt);
            }
        });
        jButtonBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox16ActionPerformed(evt);
            }
        });
        jPanelBox20.add(jButtonBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/7.png"))); // NOI18N
        jLabelBox16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox16MouseExited(evt);
            }
        });
        jPanelBox20.add(jLabelBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanelFlu.add(jPanelBox20);

        jPanelBox21.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox17.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox17.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox17.setText("detail");
        jButtonBox17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox17MouseEntered(evt);
            }
        });
        jButtonBox17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox17ActionPerformed(evt);
            }
        });
        jPanelBox21.add(jButtonBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/8.png"))); // NOI18N
        jLabelBox17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox17MouseExited(evt);
            }
        });
        jPanelBox21.add(jLabelBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanelFlu.add(jPanelBox21);

        jPanelBox22.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox18.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox18.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox18.setText("detail");
        jButtonBox18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox18MouseEntered(evt);
            }
        });
        jButtonBox18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox18ActionPerformed(evt);
            }
        });
        jPanelBox22.add(jButtonBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/9.png"))); // NOI18N
        jLabelBox18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox18MouseExited(evt);
            }
        });
        jPanelBox22.add(jLabelBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanelFlu.add(jPanelBox22);

        jPanelBox23.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox19.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox19.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox19.setText("detail");
        jButtonBox19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox19MouseEntered(evt);
            }
        });
        jButtonBox19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox19ActionPerformed(evt);
            }
        });
        jPanelBox23.add(jButtonBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/10.png"))); // NOI18N
        jLabelBox19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox19MouseExited(evt);
            }
        });
        jPanelBox23.add(jLabelBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanelFlu.add(jPanelBox23);

        jPanelBox24.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBox24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelFlu.add(jPanelBox24);

        jPanelBox25.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBox25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelFlu.add(jPanelBox25);

        jPanelBox26.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBox26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelFlu.add(jPanelBox26);

        jPanelBox27.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBox27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelFlu.add(jPanelBox27);

        jPanel2.add(jPanelFlu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 430, 410));

        jPanelBatuk.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBatuk.setLayout(new java.awt.GridLayout(3, 3, 20, 20));

        jPanelBox10.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox10.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox10.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox10.setText("detail");
        jButtonBox10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox10MouseEntered(evt);
            }
        });
        jButtonBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox10ActionPerformed(evt);
            }
        });
        jPanelBox10.add(jButtonBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/1.png"))); // NOI18N
        jLabelBox10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox10MouseExited(evt);
            }
        });
        jPanelBox10.add(jLabelBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanelBatuk.add(jPanelBox10);

        jPanelBox11.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox11.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox11.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox11.setText("detail");
        jButtonBox11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox11MouseEntered(evt);
            }
        });
        jButtonBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox11ActionPerformed(evt);
            }
        });
        jPanelBox11.add(jButtonBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/2.png"))); // NOI18N
        jLabelBox11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox11MouseExited(evt);
            }
        });
        jPanelBox11.add(jLabelBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanelBatuk.add(jPanelBox11);

        jPanelBox12.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox12.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox12.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox12.setText("detail");
        jButtonBox12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox12MouseEntered(evt);
            }
        });
        jButtonBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox12ActionPerformed(evt);
            }
        });
        jPanelBox12.add(jButtonBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/3.png"))); // NOI18N
        jLabelBox12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox12MouseExited(evt);
            }
        });
        jPanelBox12.add(jLabelBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanelBatuk.add(jPanelBox12);

        jPanelBox13.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox13.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox13.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox13.setText("detail");
        jButtonBox13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox13MouseEntered(evt);
            }
        });
        jButtonBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox13ActionPerformed(evt);
            }
        });
        jPanelBox13.add(jButtonBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/4.png"))); // NOI18N
        jLabelBox13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox13MouseExited(evt);
            }
        });
        jPanelBox13.add(jLabelBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanelBatuk.add(jPanelBox13);

        jPanelBox14.setBackground(new java.awt.Color(255, 51, 153));
        jPanelBox14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBox14.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBox14.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBox14.setText("detail");
        jButtonBox14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBox14MouseEntered(evt);
            }
        });
        jButtonBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBox14ActionPerformed(evt);
            }
        });
        jPanelBox14.add(jButtonBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelBox14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniapotek/img/5.png"))); // NOI18N
        jLabelBox14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBox14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBox14MouseExited(evt);
            }
        });
        jPanelBox14.add(jLabelBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanelBatuk.add(jPanelBox14);

        jPanelBox15.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBox15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelBatuk.add(jPanelBox15);

        jPanelBox16.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBox16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelBatuk.add(jPanelBox16);

        jPanelBox17.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBox17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelBatuk.add(jPanelBox17);

        jPanelBox18.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBox18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelBatuk.add(jPanelBox18);

        jPanel2.add(jPanelBatuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 430, 410));

        jButtonBatuk.setBackground(new java.awt.Color(242, 242, 242));
        jButtonBatuk.setText("batuk");
        jButtonBatuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatukActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonBatuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 70, 20));

        jButtonAll.setBackground(new java.awt.Color(242, 242, 242));
        jButtonAll.setText("all");
        jButtonAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAllActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 70, 20));

        jButtonFlu.setBackground(new java.awt.Color(242, 242, 242));
        jButtonFlu.setText("flu");
        jButtonFlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFluActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonFlu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 70, 20));

        jPanelRight.add(jPanel2);
        jPanel2.setBounds(20, 20, 760, 510);

        getContentPane().add(jPanelRight, java.awt.BorderLayout.CENTER);

        jPanelLeft.setPreferredSize(new java.awt.Dimension(100, 551));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelLeft, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox1MouseEntered
        // TODO add your handling code here:
        jButtonBox1.setVisible(true);
    }//GEN-LAST:event_jLabelBox1MouseEntered

    private void jLabelBox1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox1MouseExited
        // TODO add your handling code here:
        jButtonBox1.setVisible(false);
    }//GEN-LAST:event_jLabelBox1MouseExited

    private void jButtonBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox1MouseEntered
        // TODO add your handling code here:
        jButtonBox1.setVisible(true);
    }//GEN-LAST:event_jButtonBox1MouseEntered

    private void jButtonBox2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox2MouseEntered
        // TODO add your handling code here:
        jButtonBox2.setVisible(true);
    }//GEN-LAST:event_jButtonBox2MouseEntered

    private void jLabelBox2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox2MouseEntered
        // TODO add your handling code here:
         jButtonBox2.setVisible(true);
    }//GEN-LAST:event_jLabelBox2MouseEntered

    private void jLabelBox2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox2MouseExited
        // TODO add your handling code here:
         jButtonBox2.setVisible(false);
    }//GEN-LAST:event_jLabelBox2MouseExited

    private void jButtonBox3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox3MouseEntered
        // TODO add your handling code here:
         jButtonBox3.setVisible(true);
    }//GEN-LAST:event_jButtonBox3MouseEntered

    private void jLabelBox3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox3MouseEntered
        // TODO add your handling code here:
        jButtonBox3.setVisible(true);
    }//GEN-LAST:event_jLabelBox3MouseEntered

    private void jLabelBox3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox3MouseExited
        // TODO add your handling code here:
        jButtonBox3.setVisible(false);
    }//GEN-LAST:event_jLabelBox3MouseExited

    private void jButtonBox4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox4MouseEntered
        // TODO add your handling code here:
        jButtonBox4.setVisible(true);
    }//GEN-LAST:event_jButtonBox4MouseEntered

    private void jLabelBox4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox4MouseEntered
        // TODO add your handling code here:
        jButtonBox4.setVisible(true);
    }//GEN-LAST:event_jLabelBox4MouseEntered

    private void jLabelBox4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox4MouseExited
        // TODO add your handling code here:
        jButtonBox4.setVisible(false);
    }//GEN-LAST:event_jLabelBox4MouseExited

    private void jButtonBox5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox5MouseEntered
        // TODO add your handling code here:
        jButtonBox5.setVisible(true);
    }//GEN-LAST:event_jButtonBox5MouseEntered

    private void jLabelBox5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox5MouseEntered
        // TODO add your handling code here:
        jButtonBox5.setVisible(true);
    }//GEN-LAST:event_jLabelBox5MouseEntered

    private void jLabelBox5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox5MouseExited
        // TODO add your handling code here:
        jButtonBox5.setVisible(false);
    }//GEN-LAST:event_jLabelBox5MouseExited

    private void jButtonBox6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox6MouseEntered
        // TODO add your handling code here:
        jButtonBox6.setVisible(true);
    }//GEN-LAST:event_jButtonBox6MouseEntered

    private void jLabelBox6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox6MouseEntered
        // TODO add your handling code here:
        jButtonBox6.setVisible(true);
    }//GEN-LAST:event_jLabelBox6MouseEntered

    private void jLabelBox6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox6MouseExited
        // TODO add your handling code here:
        jButtonBox6.setVisible(false);
    }//GEN-LAST:event_jLabelBox6MouseExited

    private void jButtonBox7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox7MouseEntered
        // TODO add your handling code here:
        jButtonBox7.setVisible(true);
    }//GEN-LAST:event_jButtonBox7MouseEntered

    private void jLabelBox7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox7MouseEntered
        // TODO add your handling code here:
        jButtonBox7.setVisible(true);
    }//GEN-LAST:event_jLabelBox7MouseEntered

    private void jLabelBox7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox7MouseExited
        // TODO add your handling code here:
        jButtonBox7.setVisible(false);
    }//GEN-LAST:event_jLabelBox7MouseExited

    private void jButtonBox8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox8MouseEntered
        // TODO add your handling code here:
        jButtonBox8.setVisible(true);
    }//GEN-LAST:event_jButtonBox8MouseEntered

    private void jLabelBox8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox8MouseEntered
        // TODO add your handling code here:
        jButtonBox8.setVisible(true);
    }//GEN-LAST:event_jLabelBox8MouseEntered

    private void jLabelBox8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox8MouseExited
        // TODO add your handling code here:
        jButtonBox8.setVisible(false);
    }//GEN-LAST:event_jLabelBox8MouseExited

    private void jButtonBox9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox9MouseEntered
        // TODO add your handling code here:
        jButtonBox9.setVisible(true);
    }//GEN-LAST:event_jButtonBox9MouseEntered

    private void jLabelBox9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox9MouseEntered
        // TODO add your handling code here:
        jButtonBox9.setVisible(true);
    }//GEN-LAST:event_jLabelBox9MouseEntered

    private void jLabelBox9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox9MouseExited
        // TODO add your handling code here:
        jButtonBox9.setVisible(false);
    }//GEN-LAST:event_jLabelBox9MouseExited

    private void jButtonBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox1ActionPerformed
        // TODO add your handling code here:
        detail = 1;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
        jTextPaneDetail.setText("Obat Batuk Vicks 250ml\n" +
"Obat pereda nyeri dan demam\n" +
"Efektif untuk mengurangi rasa\n" +
"nyeri, aman untuk digunakan.");
        jLabelDetailTittle.setText("Obat Batuk Vicks");

    }//GEN-LAST:event_jButtonBox1ActionPerformed

    private void jButtonBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox2ActionPerformed
        // TODO add your handling code here:
        detail = 2;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
        jTextPaneDetail.setText("Obat Batuk OBH 250ml\n" +
"Obat pereda batuk anak\n" +
"Efektif untuk mengurangi rasa\n" +
"gatal pada tenggorokan, aman untuk digunakan.");
        jLabelDetailTittle.setText("Obat Batuk OBH");
    }//GEN-LAST:event_jButtonBox2ActionPerformed

    private void jButtonBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox3ActionPerformed
        // TODO add your handling code here:
        detail = 3;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
        jTextPaneDetail.setText("Obat Batuk OBH Combi 250ml\n" +
"Obat pereda batuk 250ml\n" +
"Efektif untuk mengurangi batuk\n" +
"berdahak, aman untuk digunakan.");
        jLabelDetailTittle.setText("OBH Combi");
    }//GEN-LAST:event_jButtonBox3ActionPerformed

    private void jButtonBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox4ActionPerformed
        // TODO add your handling code here:
        detail = 4;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
        jTextPaneDetail.setText("Obat Batuk Woods 200ml\n" +
"Obat pereda batuk berdahak\n" +
"khusus orang dewasa dan\n" +
"aman untuk digunakan.");
        jLabelDetailTittle.setText("Woods 200ml");
    }//GEN-LAST:event_jButtonBox4ActionPerformed

    private void jButtonBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox5ActionPerformed
        // TODO add your handling code here:
        detail = 5;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
        jTextPaneDetail.setText("Obat OB Herbal 200ml\n" +
"Obat pereda batuk berdahak\n" +
"dengan bahan alami sehingga\n" +
"aman untuk digunakan.");
        jLabelDetailTittle.setText("OB Herbal 200ml");
    }//GEN-LAST:event_jButtonBox5ActionPerformed

    private void jButtonBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox6ActionPerformed
        // TODO add your handling code here:
        detail = 6;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
        jTextPaneDetail.setText("Obat Panadol Kablet\n" +
"Obat pereda Flu Berat\n" +
"khusus orang dewasa dan\n" +
"aman untuk digunakan.");
        jLabelDetailTittle.setText("Panadol Kablet");
    }//GEN-LAST:event_jButtonBox6ActionPerformed

    private void jButtonBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox7ActionPerformed
        // TODO add your handling code here:
        detail = 7;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
        jTextPaneDetail.setText("Mixagrip Flu\n" +
"Obat pereda Flu Berat bangedd\n" +
"khusus orang dewasa dan\n" +
"aman untuk digunakan.");
        jLabelDetailTittle.setText("Mixagrip Flu Berad");
    }//GEN-LAST:event_jButtonBox7ActionPerformed

    private void jButtonBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox8ActionPerformed
        // TODO add your handling code here:
        detail = 8;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
        jTextPaneDetail.setText("Obat Decolgen\n" +
"Obat Flu Decolgen\n" +
"cocok untuk flu berad banged serta\n" +
"aman untuk digunakan.");
        jLabelDetailTittle.setText("Decolgen 50gram");
    }//GEN-LAST:event_jButtonBox8ActionPerformed

    private void jButtonBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox9ActionPerformed
        // TODO add your handling code here:
        detail = 9;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
        jTextPaneDetail.setText("Obat Inza Kablet\n" +
"Obat pereda Flu Bueradd banged\n" +
"khusus orang dewasa dan orang tua,\n" +
"serta aman untuk digunakan.");
        jLabelDetailTittle.setText("Obat Inza Kablet");
    }//GEN-LAST:event_jButtonBox9ActionPerformed

    private void jButtonBox10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox10MouseEntered
        // TODO add your handling code here:
         jButtonBox10.setVisible(true);
    }//GEN-LAST:event_jButtonBox10MouseEntered

    private void jButtonBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox10ActionPerformed
        // TODO add your handling code here:
        detail = 1;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
        jTextPaneDetail.setText("Obat Batuk Vicks 250ml\n" +
"Obat pereda nyeri dan demam\n" +
"Efektif untuk mengurangi rasa\n" +
"nyeri, aman untuk digunakan.");
        jLabelDetailTittle.setText("Obat Batuk Vicks");
        
    }//GEN-LAST:event_jButtonBox10ActionPerformed

    private void jLabelBox10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox10MouseEntered
        // TODO add your handling code here:
        jButtonBox10.setVisible(true);
    }//GEN-LAST:event_jLabelBox10MouseEntered

    private void jLabelBox10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox10MouseExited
        // TODO add your handling code here:
        jButtonBox10.setVisible(false);
    }//GEN-LAST:event_jLabelBox10MouseExited

    private void jButtonBox11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox11MouseEntered
        // TODO add your handling code here:
        jButtonBox11.setVisible(true);
    }//GEN-LAST:event_jButtonBox11MouseEntered

    private void jButtonBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox11ActionPerformed
        // TODO add your handling code here:
        detail = 2;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
        jTextPaneDetail.setText("Obat Batuk OBH 250ml\n" +
"Obat pereda batuk anak\n" +
"Efektif untuk mengurangi rasa\n" +
"gatal pada tenggorokan, aman untuk digunakan.");
        jLabelDetailTittle.setText("Obat Batuk OBH");
    }//GEN-LAST:event_jButtonBox11ActionPerformed

    private void jLabelBox11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox11MouseEntered
        // TODO add your handling code here:
        jButtonBox11.setVisible(true);
    }//GEN-LAST:event_jLabelBox11MouseEntered

    private void jLabelBox11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox11MouseExited
        // TODO add your handling code here:
        jButtonBox11.setVisible(false);
    }//GEN-LAST:event_jLabelBox11MouseExited

    private void jButtonBox12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox12MouseEntered
        // TODO add your handling code here:
        jButtonBox12.setVisible(true);
    }//GEN-LAST:event_jButtonBox12MouseEntered

    private void jButtonBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox12ActionPerformed
        // TODO add your handling code here:
        detail = 3;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
        jTextPaneDetail.setText("Obat Batuk OBH Combi 250ml\n" +
"Obat pereda batuk 250ml\n" +
"Efektif untuk mengurangi batuk\n" +
"berdahak, aman untuk digunakan.");
        jLabelDetailTittle.setText("OBH Combi");
    }//GEN-LAST:event_jButtonBox12ActionPerformed

    private void jLabelBox12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox12MouseEntered
        // TODO add your handling code here:
        jButtonBox12.setVisible(true);
    }//GEN-LAST:event_jLabelBox12MouseEntered

    private void jLabelBox12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox12MouseExited
        // TODO add your handling code here:
        jButtonBox12.setVisible(false);
    }//GEN-LAST:event_jLabelBox12MouseExited

    private void jButtonBox13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox13MouseEntered
        // TODO add your handling code here:
        jButtonBox13.setVisible(true);
    }//GEN-LAST:event_jButtonBox13MouseEntered

    private void jButtonBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox13ActionPerformed
        // TODO add your handling code here:
        detail = 4;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
        jTextPaneDetail.setText("Obat Batuk Woods 200ml\n" +
"Obat pereda batuk berdahak\n" +
"khusus orang dewasa dan\n" +
"aman untuk digunakan.");
        jLabelDetailTittle.setText("Woods 200ml");
    }//GEN-LAST:event_jButtonBox13ActionPerformed

    private void jLabelBox13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox13MouseEntered
        // TODO add your handling code here:
        jButtonBox13.setVisible(true);
    }//GEN-LAST:event_jLabelBox13MouseEntered

    private void jLabelBox13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox13MouseExited
        // TODO add your handling code here:
        jButtonBox13.setVisible(false);
    }//GEN-LAST:event_jLabelBox13MouseExited

    private void jButtonBox14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox14MouseEntered
        // TODO add your handling code here:
        jButtonBox14.setVisible(true);
    }//GEN-LAST:event_jButtonBox14MouseEntered

    private void jButtonBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox14ActionPerformed
        // TODO add your handling code here:
        detail = 5;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
        jTextPaneDetail.setText("Obat OB Herbal 200ml\n" +
"Obat pereda batuk berdahak\n" +
"dengan bahan alami sehingga\n" +
"aman untuk digunakan.");
        jLabelDetailTittle.setText("OB Herbal 200ml");
    }//GEN-LAST:event_jButtonBox14ActionPerformed

    private void jLabelBox14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox14MouseExited
        // TODO add your handling code here:
        jButtonBox14.setVisible(false);
    }//GEN-LAST:event_jLabelBox14MouseExited

    private void jLabelBox14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox14MouseEntered
        // TODO add your handling code here:
        jButtonBox14.setVisible(true);
    }//GEN-LAST:event_jLabelBox14MouseEntered

    private void jButtonBox15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox15MouseEntered
        // TODO add your handling code here:
        jButtonBox15.setVisible(true);
    }//GEN-LAST:event_jButtonBox15MouseEntered

    private void jButtonBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox15ActionPerformed
        // TODO add your handling code here:
        detail = 6;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
        jTextPaneDetail.setText("Obat Panadol Kablet\n" +
"Obat pereda Flu Berat\n" +
"khusus orang dewasa dan\n" +
"aman untuk digunakan.");
        jLabelDetailTittle.setText("Panadol Kablet");
    }//GEN-LAST:event_jButtonBox15ActionPerformed

    private void jLabelBox15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox15MouseEntered
        // TODO add your handling code here:
        jButtonBox15.setVisible(true);
    }//GEN-LAST:event_jLabelBox15MouseEntered

    private void jLabelBox15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox15MouseExited
        // TODO add your handling code here:
        jButtonBox15.setVisible(false);
    }//GEN-LAST:event_jLabelBox15MouseExited

    private void jButtonBox16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox16MouseEntered
        // TODO add your handling code here:
        jButtonBox16.setVisible(true);
    }//GEN-LAST:event_jButtonBox16MouseEntered

    private void jButtonBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox16ActionPerformed
        // TODO add your handling code here:
        detail = 7;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
        jTextPaneDetail.setText("Mixagrip Flu\n" +
"Obat pereda Flu Berat bangedd\n" +
"khusus orang dewasa dan\n" +
"aman untuk digunakan.");
        jLabelDetailTittle.setText("Mixagrip Flu Berad");
    }//GEN-LAST:event_jButtonBox16ActionPerformed

    private void jLabelBox16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox16MouseEntered
        // TODO add your handling code here:
        jButtonBox16.setVisible(true);
    }//GEN-LAST:event_jLabelBox16MouseEntered

    private void jLabelBox16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox16MouseExited
        // TODO add your handling code here:
        jButtonBox16.setVisible(false);
    }//GEN-LAST:event_jLabelBox16MouseExited

    private void jButtonBox17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox17MouseEntered
        // TODO add your handling code here:
        jButtonBox17.setVisible(true);
    }//GEN-LAST:event_jButtonBox17MouseEntered

    private void jButtonBox17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox17ActionPerformed
        // TODO add your handling code here:
        detail = 8;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
        jTextPaneDetail.setText("Obat Decolgen\n" +
"Obat Flu Decolgen\n" +
"cocok untuk flu berad banged serta\n" +
"aman untuk digunakan.");
        jLabelDetailTittle.setText("Decolgen 50gram");
    }//GEN-LAST:event_jButtonBox17ActionPerformed

    private void jLabelBox17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox17MouseEntered
        // TODO add your handling code here:
        jButtonBox17.setVisible(true);
    }//GEN-LAST:event_jLabelBox17MouseEntered

    private void jLabelBox17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox17MouseExited
        // TODO add your handling code here:
        jButtonBox17.setVisible(false);
    }//GEN-LAST:event_jLabelBox17MouseExited

    private void jButtonBox18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox18MouseEntered
        // TODO add your handling code here:
        jButtonBox18.setVisible(true);
    }//GEN-LAST:event_jButtonBox18MouseEntered

    private void jButtonBox18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox18ActionPerformed
        // TODO add your handling code here:
        detail = 9;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
        jTextPaneDetail.setText("Obat Inza Kablet\n" +
"Obat pereda Flu Bueradd banged\n" +
"khusus orang dewasa dan orang tua,\n" +
"serta aman untuk digunakan.");
        jLabelDetailTittle.setText("Obat Inza Kablet");
    }//GEN-LAST:event_jButtonBox18ActionPerformed

    private void jLabelBox18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox18MouseEntered
        // TODO add your handling code here:
        jButtonBox18.setVisible(true);
    }//GEN-LAST:event_jLabelBox18MouseEntered

    private void jLabelBox18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox18MouseExited
        // TODO add your handling code here
        jButtonBox18.setVisible(false);
    }//GEN-LAST:event_jLabelBox18MouseExited

    private void jButtonBox19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBox19MouseEntered
        // TODO add your handling code here:
        jButtonBox19.setVisible(true);
    }//GEN-LAST:event_jButtonBox19MouseEntered

    private void jButtonBox19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBox19ActionPerformed
        // TODO add your handling code here:
        detail = 10;
        ImageIcon icon = new ImageIcon("src/iniapotek/img/"+detail+".png");
        jLabelDetailGambar.setIcon(icon);
        jTextPaneDetail.setText("Obat Procold Flu\n" +
"Procold pereda Flu Bueradd banged\n" +
"khusus orang dewasa dan orang tua,\n" +
"dan aman untuk digunakan (gunakan sesuai dosis!).");
        jLabelDetailTittle.setText("Obat Inza Kablet");
    }//GEN-LAST:event_jButtonBox19ActionPerformed

    private void jLabelBox19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox19MouseEntered
        // TODO add your handling code here:
        jButtonBox19.setVisible(true);
    }//GEN-LAST:event_jLabelBox19MouseEntered

    private void jLabelBox19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBox19MouseExited
        // TODO add your handling code here:
        jButtonBox19.setVisible(false);
    }//GEN-LAST:event_jLabelBox19MouseExited

    private void jButtonAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAllActionPerformed
        // TODO add your handling code here:
        jPanelFlu.setVisible(false);
        jPanelBatuk.setVisible(false);
        jPanelFull.setVisible(true);
        
    }//GEN-LAST:event_jButtonAllActionPerformed

    private void jButtonFluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFluActionPerformed
        // TODO add your handling code here:
        
        jPanelBatuk.setVisible(false);
        jPanelFull.setVisible(false);
        jPanelFlu.setVisible(true);
    }//GEN-LAST:event_jButtonFluActionPerformed

    private void jButtonBatukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatukActionPerformed

        jPanelFull.setVisible(false);
        jPanelFlu.setVisible(false);
        jPanelBatuk.setVisible(true);
    }//GEN-LAST:event_jButtonBatukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // Mengatur Look and Feel ke FlatLightLaf
            UIManager.setLookAndFeel(new FlatLightLaf());

            // Mengatur sudut lengkung untuk tombol dan panel
//            UIManager.put("Button.border", BorderFactory.createEmptyBorder());


            UIManager.put("Button.arc", 15);  
            


            

        } catch (Exception e) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tokoObat1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAll;
    private javax.swing.JButton jButtonBatuk;
    private javax.swing.JButton jButtonBox1;
    private javax.swing.JButton jButtonBox10;
    private javax.swing.JButton jButtonBox11;
    private javax.swing.JButton jButtonBox12;
    private javax.swing.JButton jButtonBox13;
    private javax.swing.JButton jButtonBox14;
    private javax.swing.JButton jButtonBox15;
    private javax.swing.JButton jButtonBox16;
    private javax.swing.JButton jButtonBox17;
    private javax.swing.JButton jButtonBox18;
    private javax.swing.JButton jButtonBox19;
    private javax.swing.JButton jButtonBox2;
    private javax.swing.JButton jButtonBox3;
    private javax.swing.JButton jButtonBox4;
    private javax.swing.JButton jButtonBox5;
    private javax.swing.JButton jButtonBox6;
    private javax.swing.JButton jButtonBox7;
    private javax.swing.JButton jButtonBox8;
    private javax.swing.JButton jButtonBox9;
    private javax.swing.JButton jButtonFlu;
    private javax.swing.JLabel jLabelBox1;
    private javax.swing.JLabel jLabelBox10;
    private javax.swing.JLabel jLabelBox11;
    private javax.swing.JLabel jLabelBox12;
    private javax.swing.JLabel jLabelBox13;
    private javax.swing.JLabel jLabelBox14;
    private javax.swing.JLabel jLabelBox15;
    private javax.swing.JLabel jLabelBox16;
    private javax.swing.JLabel jLabelBox17;
    private javax.swing.JLabel jLabelBox18;
    private javax.swing.JLabel jLabelBox19;
    private javax.swing.JLabel jLabelBox2;
    private javax.swing.JLabel jLabelBox3;
    private javax.swing.JLabel jLabelBox4;
    private javax.swing.JLabel jLabelBox5;
    private javax.swing.JLabel jLabelBox6;
    private javax.swing.JLabel jLabelBox7;
    private javax.swing.JLabel jLabelBox8;
    private javax.swing.JLabel jLabelBox9;
    private javax.swing.JLabel jLabelDetail;
    private javax.swing.JLabel jLabelDetailGambar;
    private javax.swing.JLabel jLabelDetailTittle;
    private javax.swing.JLabel jLabelPilihObat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelBatuk;
    private javax.swing.JPanel jPanelBox1;
    private javax.swing.JPanel jPanelBox10;
    private javax.swing.JPanel jPanelBox11;
    private javax.swing.JPanel jPanelBox12;
    private javax.swing.JPanel jPanelBox13;
    private javax.swing.JPanel jPanelBox14;
    private javax.swing.JPanel jPanelBox15;
    private javax.swing.JPanel jPanelBox16;
    private javax.swing.JPanel jPanelBox17;
    private javax.swing.JPanel jPanelBox18;
    private javax.swing.JPanel jPanelBox19;
    private javax.swing.JPanel jPanelBox2;
    private javax.swing.JPanel jPanelBox20;
    private javax.swing.JPanel jPanelBox21;
    private javax.swing.JPanel jPanelBox22;
    private javax.swing.JPanel jPanelBox23;
    private javax.swing.JPanel jPanelBox24;
    private javax.swing.JPanel jPanelBox25;
    private javax.swing.JPanel jPanelBox26;
    private javax.swing.JPanel jPanelBox27;
    private javax.swing.JPanel jPanelBox3;
    private javax.swing.JPanel jPanelBox4;
    private javax.swing.JPanel jPanelBox5;
    private javax.swing.JPanel jPanelBox6;
    private javax.swing.JPanel jPanelBox7;
    private javax.swing.JPanel jPanelBox8;
    private javax.swing.JPanel jPanelBox9;
    private javax.swing.JPanel jPanelFlu;
    private javax.swing.JPanel jPanelFull;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPaneDetail;
    // End of variables declaration//GEN-END:variables
}
